DEFAULT_KEYWORDS = [
    ("小众连衣裙", "Đầm nữ ít đụng hàng"),
    ("生日约会连衣裙", "Đầm mặc sinh nhật và hẹn hò"),
    ("法式连衣裙", "Đầm nữ phong cách Pháp"),
    ("一字肩连衣裙", "Đầm trễ vai"),
    ("生日战袍试穿", "Thử đầm nổi bật mặc sinh nhật"),
    ("吊带礼服裙生日穿搭", "Đầm tiệc hai dây mặc sinh nhật"),
    ("气质小黑裙", "Đầm đen nữ tính thanh lịch"),
    ("纯欲辣妹连衣裙", "Đầm nữ tính quyến rũ trẻ trung"),
    ("小个子连衣裙", "Đầm cho người thấp"),
]

LEGACY_KEYWORDS = {
    "晚礼服",
    "宴会礼服",
    "敬酒服",
    "生日礼服",
    "高级感连衣裙",
    "法式礼服",
    "显瘦礼服",
    "小个子礼服",
    "新中式礼服",
    "年会礼服",
    "轻礼服连衣裙女",
    "小众设计感连衣裙女",
    "生日战袍连衣裙女",
    "法式收腰连衣裙女",
    "一字肩花朵连衣裙",
    "抹胸蝴蝶结连衣裙",
    "吊带网纱长裙女",
    "气质小黑裙女",
    "梨形身材显瘦连衣裙",
    "小个子显高连衣裙",
    "轻礼服女",
    "生日战袍",
    "梨形身材连衣裙",
    "抹胸连衣裙",
    "吊带长裙",
    "轻熟风连衣裙",
    "抹胸连衣裙试穿",
    "吊带连衣裙试穿",
    "抹胸礼服裙试穿",
    "吊带约会礼服裙",
}

SETTING_KEYS = {
    "usd_vnd_rate": "26000",
    "cost_per_search_usd": "0.01",
    "cost_per_stats_usd": "0.025",
    "max_requests_per_run": "35",
    "max_requests_per_month": "400",
    "pages_per_keyword": "3",
    "max_detail_videos_per_run": "50",
    "search_sort_type": "0",
    "search_publish_time": "7",
    "search_content_type": "1",
    "tikhub_search_endpoint": "/api/v1/douyin/search/fetch_video_search_v2",
    "tikhub_use_fallback_search": "false",
    "scheduler_enabled": "false",
    "scheduler_hour": "9",
    "scheduler_minute": "0",
    "internal_rate_limit_rps": "2.0",
}
